name: "nowcrm"

services:
  dbdt:
    container_name: strapidb
    image: postgres:17.2
    restart: always
    command: -c 'max_connections=500'
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${STRAPI_DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${STRAPI_DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${STRAPI_DATABASE_NAME:-postgres}
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${STRAPI_DATABASE_USERNAME} -d ${STRAPI_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my_net

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PORT: ${REDIS_PORT:-6379}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - my_net

  strapi:
    container_name: strapi
    image: nowcrm-strapi
    build: ./apps/nowcrm-strapi/
    restart: unless-stopped
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: ${STRAPI_DATABASE_CLIENT}
      DATABASE_HOST: dbdt
      DATABASE_PORT: ${STRAPI_DATABASE_PORT}
      DATABASE_NAME: ${STRAPI_DATABASE_NAME}
      DATABASE_USERNAME: ${STRAPI_DATABASE_USERNAME}
      DATABASE_PASSWORD: ${STRAPI_DATABASE_PASSWORD}
      DATABASE_RDS: ${STRAPI_DATABASE_RDS}
      ADMIN_JWT_SECRET: ${STRAPI_ADMIN_JWT_SECRET}
      API_TOKEN_SALT: ${STRAPI_API_TOKEN_SALT}
      APP_KEYS: ${STRAPI_APP_KEYS}
      DATABASE_SSL_CERT: ${STRAPI_DATABASE_SSL_CERT}
      DATABASE_SSL_CA: ${STRAPI_DATABASE_SSL_CA}
      DATABASE_SSL_CAPATH: ${STRAPI_DATABASE_SSL_CAPATH}
      DATABASE_SSL_CIPHER: ${STRAPI_DATABASE_SSL_CIPHER}
      DATABASE_SSL_REJECT_UNAUTHORIZED: ${STRAPI_DATABASE_SSL_REJECT_UNAUTHORIZED}
      DATABASE_SCHEMA: ${STRAPI_DATABASE_SCHEMA}
      DATABASE_POOL_MIN: ${STRAPI_DATABASE_POOL_MIN}
      DATABASE_POOL_MAX: ${STRAPI_DATABASE_POOL_MAX}
    volumes:
      - ./apps/nowcrm-strapi/src:/opt/app/src
    depends_on:
      - dbdt
    networks:
      - my_net

  nowcrm:
    container_name: nowcrm
    image: nowcrm
    build: ./contactsapp/
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      AUTH_SECRET: ${CRM_AUTH_SECRET}
      AUTH_TRUST_HOST: ${CRM_AUTH_TRUST_HOST}
      AUTH_URL: ${CRM_AUTH_URL}
      CRM_BASE_URL: ${CRM_BASE_URL}
      CRM_COMPOSER_API_URL: ${CRM_COMPOSER_API_URL}
      CRM_DAL_API_URL: ${CRM_COMPOSER_DAL_URL}
      CRM_STRAPI_API_TOKEN: ${CRM_STRAPI_API_TOKEN}
      CRM_STRAPI_API_URL: ${CRM_STRAPI_API_URL}
    depends_on:
      - strapi
    networks:
      - my_net

  journeys:
    container_name: journeys
    image: nowcrm-journeys
    build:
      context: .
      dockerfile: ./apps/journeys/Dockerfile
    restart: unless-stopped
    ports:
      - "3010:3010"
    environment:
      JOURNEYS_HOST: ${JOURNEYS_HOST}
      JOURNEYS_PORT: ${JOURNEYS_PORT}
      JOURNEYS_CHECK_TIME: ${JOURNEYS_CHECK_TIME}
      JOURNEYS_COMMON_RATE_LIMIT_MAX_REQUESTS: ${JOURNEYS_COMMON_RATE_LIMIT_MAX_REQUESTS}
      JOURNEYS_CORS_ORIGIN: ${JOURNEYS_CORS_ORIGIN}
      JOURNEYS_JOB_COMPLETED_LIFE_TIME_DAYS: ${JOURNEYS_JOB_COMPLETED_LIFE_TIME_DAYS}
      JOURNEYS_JOB_FAIL_LIFE_TIME_DAYS: ${JOURNEYS_JOB_FAIL_LIFE_TIME_DAYS}
      JOURNEYS_MINUTE_TO_LAUNCH: ${JOURNEYS_MINUTE_TO_LAUNCH}
      JOURNEYS_REDIS_HOST: ${JOURNEYS_REDIS_HOST}
      JOURNEYS_REDIS_PASSWORD: ${JOURNEYS_REDIS_PASSWORD}
      JOURNEYS_REDIS_PORT: ${JOURNEYS_REDIS_PORT}
      JOURNEYS_SESSION_SECRET: ${JOURNEYS_SESSION_SECRET}
      JOURNEYS_STRAPI_API_TOKEN: ${JOURNEYS_STRAPI_API_TOKEN}
      NODE_ENV: ${NODE_ENV}
      RABBITMQ_URL: ${RABBITMQ_URL}
      COMPOSER_URL: ${COMPOSER_URL}
      STRAPI_URL: ${STRAPI_URL}
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - my_net

  composer:
    container_name: composer
    image: nowcrm-composer
    build:
      context: .
      dockerfile: ./apps/composer/Dockerfile
    restart: unless-stopped
    ports:
      - "3020:3020"
    environment:
      COMPOSER_ANTHROPIC_KEY: ${COMPOSER_ANTHROPIC_KEY}
      COMPOSER_BASIC_AUTH_PASSWORD: ${COMPOSER_BASIC_AUTH_PASSWORD}
      COMPOSER_BASIC_AUTH_USERNAME: ${COMPOSER_BASIC_AUTH_USERNAME}
      COMPOSER_COMMON_RATE_LIMIT_MAX_REQUESTS: ${COMPOSER_COMMON_RATE_LIMIT_MAX_REQUESTS}
      COMPOSER_CORS_ORIGIN: ${COMPOSER_CORS_ORIGIN}
      COMPOSER_CRM_REDIRECT_HEALTH_CHECK: ${COMPOSER_CRM_REDIRECT_HEALTH_CHECK}
      COMPOSER_CUSTOMER_IDENTITY: ${COMPOSER_CUSTOMER_IDENTITY}
      COMPOSER_HOST: ${COMPOSER_HOST}
      COMPOSER_OPENAI_API_KEY: ${COMPOSER_OPENAI_API_KEY}
      COMPOSER_PORT: ${COMPOSER_PORT}
      COMPOSER_REDIS_HOST: ${COMPOSER_REDIS_HOST}
      COMPOSER_REDIS_PASSWORD: ${COMPOSER_REDIS_PASSWORD}
      COMPOSER_REDIS_PORT: ${COMPOSER_REDIS_PORT}
      COMPOSER_SESSION_SECRET: ${COMPOSER_SESSION_SECRET}
      COMPOSER_SMTP_HOST: ${COMPOSER_SMTP_HOST}
      COMPOSER_SMTP_PASS: ${COMPOSER_SMTP_PASS}
      COMPOSER_SMTP_PORT: ${COMPOSER_SMTP_PORT}
      COMPOSER_SMTP_USER: ${COMPOSER_SMTP_USER}
      COMPOSER_STRAPI_API_TOKEN: ${COMPOSER_STRAPI_API_TOKEN}
      COMPOSER_STRAPI_API_URL: ${COMPOSER_STRAPI_API_URL}
      CUSTOMER_DOMAIN: ${CUSTOMER_DOMAIN}
      NODE_ENV: ${NODE_ENV}
      SHARED_COMPOSER_URL: ${SHARED_COMPOSER_URL}
      SHARED_STRAPI_URL: ${SHARED_STRAPI_URL}
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - my_net

  dal:
    container_name: nowcrm-dal
    image: nowcrm-dal
    build:
      context: .
      dockerfile: ./apps/dal/Dockerfile
    restart: unless-stopped
    ports:
      - "6001:6001"
    environment:
      DAL_BASIC_AUTH_PASSWORD: ${DAL_BASIC_AUTH_PASSWORD}
      DAL_BASIC_AUTH_USERNAME: ${DAL_BASIC_AUTH_USERNAME}
      DAL_CHECK_TIME: ${DAL_CHECK_TIME}
      DAL_COMMON_RATE_LIMIT_MAX_REQUESTS: ${DAL_COMMON_RATE_LIMIT_MAX_REQUESTS}
      DAL_CORS_ORIGIN: ${DAL_CORS_ORIGIN}
      DAL_DATABASE_CLIENT: ${DAL_DATABASE_CLIENT}
      DAL_DATABASE_HOST: ${DAL_DATABASE_HOST}
      DAL_DATABASE_NAME: ${DAL_DATABASE_NAME}
      DAL_DATABASE_PASSWORD: ${DAL_DATABASE_PASSWORD}
      DAL_DATABASE_PORT: ${DAL_DATABASE_PORT}
      DAL_DATABASE_RDS: ${DAL_DATABASE_RDS}
      DAL_DATABASE_SSL_SELF: ${DAL_DATABASE_SSL_SELF}
      DAL_DATABASE_USERNAME: ${DAL_DATABASE_USERNAME}
      DAL_HOST: ${DAL_HOST}
      DAL_JOB_COMPLETED_LIFE_TIME_DAYS: ${DAL_JOB_COMPLETED_LIFE_TIME_DAYS}
      DAL_JOB_CONCURRENCY: ${DAL_JOB_CONCURRENCY}
      DAL_JOB_FAIL_LIFE_TIME_DAYS: ${DAL_JOB_FAIL_LIFE_TIME_DAYS}
      DAL_MINUTE_TO_LAUNCH: ${DAL_MINUTE_TO_LAUNCH}
      DAL_PORT: ${DAL_PORT}
      DAL_REDIS_HOST: ${DAL_REDIS_HOST}
      DAL_REDIS_PASSWORD: ${DAL_REDIS_PASSWORD}
      DAL_REDIS_PORT: ${DAL_REDIS_PORT}
      DAL_SESSION_SECRET: ${DAL_SESSION_SECRET}
      DAL_SMTP_FROM: ${DAL_SMTP_FROM}
      DAL_SMTP_HOST: ${DAL_SMTP_HOST}
      DAL_SMTP_PASS: ${DAL_SMTP_PASS}
      DAL_SMTP_PORT: ${DAL_SMTP_PORT}
      DAL_SMTP_USER: ${DAL_SMTP_USER}
      DAL_STRAPI_API_TOKEN: ${DAL_STRAPI_API_TOKEN}
      DAL_STRAPI_API_URL: ${DAL_STRAPI_API_URL}
      DAL_WORKER_COUNT: ${DAL_WORKER_COUNT}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - my_net

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1.2-management
    restart: always
    command: >
      bash -c "
      cp /custom_plugins/rabbitmq_delayed_message_exchange-4.1.0.ez /opt/rabbitmq/plugins/ &&
      rabbitmq-plugins enable rabbitmq_delayed_message_exchange &&
      rabbitmq-plugins enable rabbitmq_management &&
      rabbitmq-server"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq:/custom_plugins
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - my_net

  mailpit:
    container_name: mailpit
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - my_net

volumes:
  postgres-data:
  rabbitmq_data:
  redis_data:

networks:
  my_net:
    external: true
