name: "nowcrm"

services:
  dbdt:
    container_name: strapidb
    image: postgres:17.2
    restart: always
    command: -c 'max_connections=500'
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${STRAPI_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${STRAPI_DATABASE_PASSWORD}
      POSTGRES_DB: ${STRAPI_DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${STRAPI_DATABASE_USERNAME} -d ${STRAPI_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my_net

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PORT: ${REDIS_PORT:-6379}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - my_net

  strapi:
    container_name: strapi
    image: nowcrm-strapi
    build: ./apps/nowcrm-strapi/
    restart: unless-stopped
    ports:
      - "1337:1337"
    environment:
      TEST_RUN: ${TEST_RUN}
      DATABASE_CLIENT: ${STRAPI_DATABASE_CLIENT}
      DATABASE_HOST: dbdt
      DATABASE_PORT: ${STRAPI_DATABASE_PORT}
      DATABASE_NAME: ${STRAPI_DATABASE_NAME}
      DATABASE_USERNAME: ${STRAPI_DATABASE_USERNAME}
      DATABASE_PASSWORD: ${STRAPI_DATABASE_PASSWORD}
      DATABASE_RDS: ${STRAPI_DATABASE_RDS}
      ADMIN_JWT_SECRET: ${STRAPI_ADMIN_JWT_SECRET}
      API_TOKEN_SALT: ${STRAPI_API_TOKEN_SALT}
      APP_KEYS: ${STRAPI_APP_KEYS}
      TRANSFER_TOKEN_SALT: ${STRAPI_TRANSFER_TOKEN_SALT}
      DATABASE_SSL: ${STRAPI_DATABASE_SSL}
      DATABASE_SSL_CERT: ${STRAPI_DATABASE_SSL_CERT}
      DATABASE_SSL_CA: ${STRAPI_DATABASE_SSL_CA}
      DATABASE_SSL_CAPATH: ${STRAPI_DATABASE_SSL_CAPATH}
      DATABASE_SSL_CIPHER: ${STRAPI_DATABASE_SSL_CIPHER}
      DATABASE_SSL_REJECT_UNAUTHORIZED: ${STRAPI_DATABASE_SSL_REJECT_UNAUTHORIZED}
      DATABASE_SCHEMA: ${STRAPI_DATABASE_SCHEMA}
      DATABASE_SSL_KEY: ${STRAPI_DATABASE_SSL_KEY}
      DATABASE_POOL_MIN: ${STRAPI_DATABASE_POOL_MIN}
      DATABASE_POOL_MAX: ${STRAPI_DATABASE_POOL_MAX}
      STRAPI_TEST_ADMIN_EMAIL: ${STRAPI_TEST_ADMIN_EMAIL}
      STRAPI_TEST_ADMIN_PASSWORD: ${STRAPI_TEST_ADMIN_PASSWORD}
    volumes:
      - ./apps/nowcrm-strapi/src:/opt/app/src
    depends_on:
      - dbdt
    networks:
      - my_net
    
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1.2-management
    restart: always
    command: >
      bash -c "
      cp /custom_plugins/rabbitmq_delayed_message_exchange-4.1.0.ez /opt/rabbitmq/plugins/ &&
      rabbitmq-plugins enable rabbitmq_delayed_message_exchange &&
      rabbitmq-plugins enable rabbitmq_management &&
      rabbitmq-server"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq:/custom_plugins
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - my_net

volumes:
  postgres-data:
  rabbitmq_data:
  redis_data:

networks:
  my_net:
    external: true
